---
# General information
authors:
- Alexander Jaust
- Benjamin Uekermann
course_title: Simulation Software Engineering
term: Winter 2021/22
keywords:
- research software engineering
- documentation
- testing
- virtualization

# Sections to use
# The order in the list defines the order of the chapter to appear in the final document.
sections:
- 00-introduction/chapter.tex
- 02-virtualization-and-containers/chapter.tex

# Bibliography
# Several files can be specified via a list
bibliography:
- bibliography.bib
#- sample.bib

# Appendix
# appendix:
# - A01-appendix/chapter.tex

# Other settings
wrap: off

#mainfont: XITS
#sansfont: Roboto #Roboto is the font from the homepage
sansfont: Source Sans Pro
#monofont: Source Code Pro
---